play=JOGAR
about=Sobre
authors=Autores:
contributors=Colaboradores:
close=Fechar
complete=COMPLETO
congratulation=Parabéns!
you-loose=VOCÊ PERDEU
try-it-again=Tente de novo!
Turtle-Easy=Tartaruga - FÁCIL
Flower-Medium=Flor - MÉDIO
Spider-Hard=Aranha - DIFÍCIL
Cloud-Inferno=Nuvem - INFERNO
Bug-Easy=Inseto - FÁCIL
FourHills-Tricky=Quatro Colinas - COMPLICADO
startNewGame=Começar novo jogo
changeTheme=Mudar tema
gameStatistics=Estatísticas do jogo
resumeGame=Voltar ao jogo
statistics=Estatísticas
numberOfGamesWon=Jogos vencidos:
from= de
numberOfGamesWonWithUndoOrHints=Jogos vencidos sem dicas:
highScore=Recorde
achievements=Conquistas
layoutTurtle=Venceu: tabuleiro "tartaruga"
layoutFlower=Venceu: tabuleiro "flor"
layoutSpider=Venceu: tabuleiro "aranha"
layoutCloud=Venceu: tabuleiro "nuvem"
layoutBug=Venceu: tabuleiro "inseto"
layoutFourHills=Venceu: tabuleiro "quatro colinas"
gameWonUnder8Minutes=Jogo vencido em menos de 8 minutos
gameWonWithoutHints=Jogo vencido sem dicas
gameWonWithoutUndo=Jogo vencido sem desfazer
1gameWon=Pelo menos 1 jogo vencido
5gamesWon=Pelo menos 5 jogos vencidos
10gamesWon=Pelo menos 10 jogos vencidos
back-to-menu=Voltar ao menu
points=Pontos:
chooseLayout=Escolha um tabuleiro
closeStatistics=Fechar estatísticas
gamePaused=Jogo Pausado
